### ISSUE TITLE
ShazamScrobbler like functionality possible?

### ISSUE THREAD

**Issue by jbwharris** [nrubin29/finale#1]
Is it possible to bring a [ShazamScrobbler](https://shazamscrobbler.com/)-like functionality to Finale? The ability to just put the app in listening mode that'll just listen for a new song say every 3 minutes. I would absolutely love this in my car to be able to listen to regular radio and autoscrobble tracks.

**Comment by nrubin29** [comment]
Interesting idea! I'd have to take a look into if that's possible, especially on iOS because Apple is very strict about this kind of stuff. I'd imagine it would only work while the screen is on and the app is in the foreground, which definitely isn't desirable, but I'll look into seeing if this is possible.

**Comment by nrubin29** [comment]
An initial implementation of this feature has been added to v1.2.0+8! Check it out when it's live on the App Store and Play Store and let me know what you think. I couldn't figure out how to get the microphone to continue working when the device is locked, and I'm not even sure if it's possible. I can keep looking into it.

**Comment by jbwharris** [comment]
Can't wait to give that a try!

**Comment by jbwharris** [comment]
![image](https://user-images.githubusercontent.com/2962327/116689058-988c2d00-a985-11eb-9213-424316f41b40.png)

I just have this feature a try and did get a triple scrobble. It worked for the first song not sending multiples, but not the second song. 

Is there a way you could have a setting to keep the screen on if connected to a charger? I beleive Marvis Pro has a setting like that.

**Comment by nrubin29** [comment]
@jbwharris I fixed the double-scrobbling bug in version 1.2.1, which is currently awaiting approval and should release soon. The device will also stay awake on the continuous scrobbling page. Please let me know if your issues are resolved once the new update is released.

**Comment by jbwharris** [comment]
I just tried the new version and am so pleased, you'll probably notice the reddit post I just made about it.

I had a few more points of feedback to offer. 

You'll notice the song Change it scrobbled it 3 times because midway through the song it identified the extended version, then identified the regular version again. Not sure if there's much you could do about that. 
![image](https://user-images.githubusercontent.com/2962327/117167136-fdd08b80-ad94-11eb-9279-3ba8423a7b12.png)

I feel like some of that could be solved by having a setting like Neptunes on macOS has, where it strips all the extraneous remaster tags from a song before sending. So if it were doing that, it wouldn't be matching slight variant differences of what's essentially the same song. 

![image](https://user-images.githubusercontent.com/2962327/117167705-7d5e5a80-ad95-11eb-944b-2bd722b0ac7c.png)

**Comment by nrubin29** [comment]
Thanks for the suggestion! I just added the feature you requested and it'll be live in the App Store and Play Store in a few days. I tested it with 96 Tears and it correctly strips the (Album Version) tag. Unfortunately, the "Extended Version" in Change isn't formatted like a tag (no () or []), so it won't get stripped. I don't think there's much that I can do at that point; it's the fault of the music recognition service that I'm using (ACRCloud).

**Comment by jbwharris** [comment]
That's awesome. I figured it might be a complex problem to sort out given the inconsistency of those tags I've witnessed. 

I have been using this feature pretty extensively since it launched and I absolutely love it. Sure there have been some duplicate scrobbles along the way, but I've just found it works quite well for listening to radio in the car. It doesn't seem to kill the battery too badly when running, and doesn't seem to chew data either. I guess in comparison to streaming Apple Music on the fly it would use significantly less data just doing the periodical listen and send for recognition. Thanks for making this feature a reality, it's so great.

**Comment by nrubin29** [comment]
Great to hear that you're enjoying the automatic scrobbling feature! It's a great idea and a lot of other people seem to like it, so thanks for suggesting it! Hopefully the new "Strip tags" setting will help with (some of) the double scrobbles. I'm still looking into making the automatic scrobbler work when the device is locked, but no guarantees there. Let me know if you have any further suggestions to improve the automatic scrobbler or the app in general.

**Comment by jbwharris** [comment]
I did have a suggestion that is probably really narrow as far who might find it useful. I'd love to be able to scrobble to multiple last.fm accounts(or a libre.fm account). I have [this setup](https://www.reddit.com/r/lastfm/comments/m04btp/syncing_external_listensradio_streaming_etc_to/) that basically allows me to pull in music I listen to outside of Apple Music into AM via a playlist. At its root I need it to be able to scrobble to 2 accounts, one being my main account to count the scrobble, then the second is just stuff I listen to with Web Scrobbler. I know libre.fm(or ListenBrainz for that matter) there isn't even a scrobbler that works for iOS, so there might be an appetite for something that integrates with those services.
