### ISSUE TITLE
Selecting specific tracks for manual scrobbling

### ISSUE THREAD

**Issue by woojink** [nrubin29/finale#10]
I've been really appreciating the album search + manual scrobbling feature for offline listening and unsupported devices. I was wondering if it would be possible to select specific tracks before scrobbling (e.g. scrobbling from where one paused previously, only scrobbling disc 1, etc.). Much thanks for the app! Cheers,

**Comment by nrubin29** [comment]
Great idea! I'll add it to my list.

**Comment by nrubin29** [comment]
This feature is part of [v2.1.0+28](https://github.com/nrubin29/finale/releases/tag/v2.1.0%2B28) which is available on web now and will be available on other platforms once approved.
