### ISSUE TITLE
Custom Period doesn't generate grid

### ISSUE THREAD

**Issue by jbwharris** [nrubin29/finale#19]
This has been a long-term issue I've experienced. I'm using iOS 15.4, but it's been around for awhile. If I generate a grid for Artist and choose Custom Period(like say Jan 1-now) and hit generate it never pulls any photos or progresses any further. Though if I choose any of the preset periods it works fine.

**Comment by nrubin29** [comment]
I just tried it myself and it works for me. It stays stuck at 0 items loaded for a bit, then it loads the rest of the way pretty quickly. How long did you wait?

I should definitely add a message about custom periods taking longer to load. Thanks for pointing this out.

**Comment by jbwharris** [comment]
I just tested it and it took 3 minutes, but it finally did load. Guess I've always been too impatient when seeing the other grids start to load the images almost right away, I assumed something wasn't working.
