### ISSUE TITLE
Scrobble icon is not visible in search listings

### ISSUE THREAD

**Issue by llacb47** [nrubin29/finale#23]
![image](https://user-images.githubusercontent.com/16567977/192411563-6ce73cbf-68ee-469d-a37c-9826a38b52f3.png)

![image](https://user-images.githubusercontent.com/16567977/192411280-bd5db7ba-cc2f-4471-98b3-8bac926e6fc7.png)

Tested in Firefox and Edge. The scrobble icon is missing its dark background and is not visible on the white background of the table rows. It only becomes visible when hovering where it should be. This only started happening in the last couple of days.

**Comment by nrubin29** [comment]
Hello, thanks for reporting this issue! It was caused by the latest update, which I have only pushed to web so far. I plan to fix the issue before publishing to other platforms. In the meantime, the button is still there, just invisible. Sorry for the confusion!

**Comment by nrubin29** [comment]
This issue has been fixed and deployed to web.

**Comment by llacb47** [comment]
Thank you!
