### ISSUE TITLE
Add libre.fm/listenbrainz support

### ISSUE THREAD

**Issue by jbwharris** [nrubin29/finale#4]
Is it possible to add the ability to scrobble to multiple services? I use both last.fm and libre.fm and can do this with [Web Scrobbler](https://github.com/web-scrobbler/web-scrobbler) and I'd love to be able to do it on iOS/iPadOS as well. From what I can tell there isn't an actual scrobbler client for libre.fm/ListenBrainz, so this would fill a bit of a gap on the platform. [Simple last.fm scrobbler](https://github.com/4-Eyes/sls) and [Pano Scrobbler](https://play.google.com/store/apps/details?id=com.arn.scrobble&hl=en_US&gl=US) does this on Android, so the functionality does exist on other platforms with some precedent. 

Seeing how [DeaDBeeF](https://github.com/DeaDBeeF-Player/deadbeef)  handles libre.fm integration, it's really just seems like submitting to another API url, just like how it's done with last.fm. 

![Screen Shot 2021-06-14 at 1 07 06 PM](https://user-images.githubusercontent.com/2962327/121931336-7d953280-cd11-11eb-8a90-acfccd9f10b6.png)

**Comment by nrubin29** [comment]
I took a quick look at this and it seems like libre.fm's API [doesn't support scrobbling](https://git.gnu.io/foocorp/librefm/-/wikis/Librefm_API#submitting-tracks). If I'm mistaken, could you point me to some documentation?

**Comment by jbwharris** [comment]
There's 2 apps that I know that scrobble to libre.fm

[DeaDBeeF scrobbler plugin](https://github.com/DeaDBeeF-Player/deadbeef/blob/df4e304a1c0f682c8e623d482085989f17e561ef/plugins/lastfm/lastfm.c) 

[Web Scrobbler libre.fm scrobbler](https://github.com/web-scrobbler/web-scrobbler/blob/master/src/core/background/scrobbler/librefm-scrobbler.js)

In both cases I believe all they're really doing is changing the API call URL they're sending the scrobbles to, from last.fm to https://libre.fm/2.0/ or  http://turtle.libre.fm, otherwise the data it's passing via that URL seems to mirror how last.fm handles it.

**Comment by nrubin29** [comment]
I cannot for the life of me figure out how to get an API key for Libre.fm. There's nothing in the docs or on the website, and I even tried joining their IRC channel but it's empty (unless I joined it wrong).

Would connecting your Last.fm account to Libre.fm be sufficient? See [here](https://git.gnu.io/foocorp/librefm/-/wikis/Clients#multi-scrobbling-from-single-server-clients).

**Comment by jbwharris** [comment]
I have posed this question to the Git for [Web Scrobbler](https://github.com/web-scrobbler/web-scrobbler/issues/2955) and I'll see what I hear back. I figure since they've done it, they might have some additional insight on the process. 

As for connecting last.fm to libre.fm, that's kind of the root need I have. It can't sync last.fm to libre.fm, but it can scrobble from libre.fm to the connected last.fm account. So how I'm using that is to scrobble to a second last.fm account. The purpose of that is to allow me to separate the things I listen to on web radio from what I listen to overall. By doing this, I can then import the things I listen to in Web Scrobbler to my Apple Music account(or Spotify or whatever else) using SongShift. [I outlined the process in detail awhile back on reddit](https://www.reddit.com/r/lastfm/comments/m04btp/syncing_external_listensradio_streaming_etc_to/). 

Why I care about this is it's truly amazing in execution once you get this flow working. By being able to import the music I'm truly listening to outside the scope of Apple Music, I can begin to inform the algorithms of what I actually like and am listening to, so then my playlists tend to get better. With how much I use the continuous listen mode in Finale, I'd love to add this stream of scrobbles into that second stream that imports into Apple Music.

**Comment by nrubin29** [comment]
Thanks for the additional information and for looking into this. If I'm able to get an API key, I'd be happy to add support for Libre.fm. Just to be sure, you would want every scrobble that the app sends to Last.fm to also go to Libre.fm, correct?

**Comment by nrubin29** [comment]
It actually looks like you don't even need a Libre.fm API key to use their API (yikes!). I implemented Libre.fm scrobbling in commit https://github.com/nrubin29/finale/commit/2011e1b08e4ce631fe9487380deec3e501612398 and it seems to work, but the site is pretty slow to load and sometimes requires multiple reloads to get a response. Are you able to build the app for yourself and test it? If not, I can just release the update and fix any issues that we find. I'd prefer to have a Libre.fm API key before releasing the update since Libre.fm says "**Unknown client**...wants your permission to talk with this service", but it isn't a big deal.

**Comment by jbwharris** [comment]
> Thanks for the additional information and for looking into this. If I'm able to get an API key, I'd be happy to add support for Libre.fm. Just to be sure, you would want every scrobble that the app sends to Last.fm to also go to Libre.fm, correct?

Yes, it would be submitting the same scrobbles to both services.

**Comment by jbwharris** [comment]
I gave it go trying to setup Flutter, but I'm running into some errors that are over my head to figure out.

**Comment by jbwharris** [comment]
I finally got a response about the Libre.fm API key. I was pointed to this thread about it. 

https://github.com/web-scrobbler/web-scrobbler/issues/1421#issuecomment-334502398

**Comment by nrubin29** [comment]
@jbwharris  Glad to hear it's working for you. I just released the update on iOS and Android. It should show up soon.

**Comment by icyphox** [comment]
Hey, any chance you could add in support for [Listenbrainz](https://listenbrainz.readthedocs.io/en/v-2021-11-25.0/)?

**Comment by jbwharris** [comment]
I know Web Scrobbler has support for ListenBrainz as well. So I'd figure the same code setup for submitting there would be in place, as it was with Libre.fm

**Comment by mattl** [comment]
@nrubin29 Thanks for adding support to Finale for Libre.fm

It would be great if you could log in to the app with a Libre.fm account as we already support federating scrobbles to Last.fm since 2009.

Also, we should get you an official client code.
