### ISSUE TITLE
Compatibility with Apple Shortcuts?

### ISSUE THREAD

**Issue by jbwharris** [nrubin29/finale#8]
I was playing with [Apple Shortcuts](https://support.apple.com/en-ca/guide/shortcuts/welcome/ios) for automations and was wondering if it was possible to add support for that in Finale? The action I wanted more than anything was being able to launch Finale and have it go right to Recognize Continuously mode. I wasn't sure since this is a Flutter app meant to work cross platform whether it would even be possible to add Shortcuts support. 

Another idea I had that would essentially be able to achieve the same goal is a setting in the preferences that defaults to Recognize Continuously mode automatically. That's my typical use case, I'm firing it up to listen to something, then secondary would be seeing my latest scrobbles like it currently defaults to. Shortcuts allows me to launch an app, so if it was already in the mode I needed right away, there'd be no issue with doing other fun automation stuff.

**Comment by nrubin29** [comment]
With the latest update, navigating to the URL `finale:///scrobbleContinuously` (yes, three slashes) will actually trigger the continuous scrobbler. You can also do `finale:///scrobbleOnce`. Can you have a shortcut launch these URLs?

**Comment by jbwharris** [comment]
I think that could totally work. I know a lot of shortcuts pertain to launching URLs

**Comment by nrubin29** [comment]
Cool! Let me know if it works for you.

**Comment by nrubin29** [comment]
In the next update after version 2.0.0, URLs will have two slashes instead of three: `finale://scrobbleOnce`, `finale://scrobbleContinuously`. (Changed in https://github.com/nrubin29/finale/commit/cce9a494f2f28358cfec4da6ed4efed4d63bd28e)

**Comment by nrubin29** [comment]
This above-mentioned change is part of [v2.1.0+28](https://github.com/nrubin29/finale/releases/tag/v2.1.0%2B28) will be available on iOS once approved.

**Comment by jbwharris** [comment]
I finally got around to trying this out and I could get it to work. I'll probably put together a post to share my results soon. Thanks for sorting this out, this could be super handy with a little ingenuity.
